---
apiVersion: v1
kind: pod
metadata:
 name: web
 labels:
  name: web
  tier: frontend
spec:
 containers:
 - name: web
   imagepullpolicy: Always
   image: techworldwithsiva/web:k8
   resources:
    request:
     cpu: "100m"
     memory: "128mi"
    limits:
     cpu: "100m"
     memory: "128mi" 
   ports:
    - containerport: 80
---
apiVersion: v1
kind: Service
metadata:
 name: web-service
spec:
 type: LoadBalancer
 selector:
  name: web
  tier: frontend
 ports:
  - protocol: TCP
    port: 80
    targetport: 80